# Generated by Django 5.0.6 on 2024-07-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('publisher', models.CharField(max_length=255, verbose_name='Editora')),
                ('language', models.CharField(max_length=50, verbose_name='Idioma')),
                ('cover_type', models.CharField(max_length=50, verbose_name='Tipo de Capa')),
                ('pages', models.PositiveIntegerField(verbose_name='Número de Páginas')),
                ('dimensions', models.CharField(max_length=50, verbose_name='Dimensões')),
                ('publication_date', models.DateField(verbose_name='Data de Publicação')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Antigo')),
                ('edition_type', models.CharField(max_length=50, verbose_name='Tipo de Edição')),
            ],
        ),
    ]
