# Generated by Django 5.0.6 on 2024-07-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='old_price',
        ),
    ]
