# Generated by Django 5.0.6 on 2024-07-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_book_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de Capa'),
        ),
        migrations.AlterField(
            model_name='book',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, verbose_name='Dimensões'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de Edição'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=50, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, verbose_name='Número de Páginas'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, verbose_name='Editora'),
        ),
    ]
