# Generated by Django 5.0.6 on 2024-07-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_photo_alter_book_cover_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='promotion',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Capa'),
        ),
        migrations.AlterField(
            model_name='book',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dimensões'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Edição'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Páginas'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Editora'),
        ),
    ]
