# Generated by Django 5.0.6 on 2024-07-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_book_promotion_alter_book_cover_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='trending',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
