# Generated by Django 5.0.6 on 2024-07-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_trending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='promotion',
            new_name='discount',
        ),
    ]
