# Generated by Django 5.0.6 on 2024-07-13 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_post_alter_book_photo_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.rating', verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
