# Generated by Django 5.0.6 on 2024-07-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='post',
        ),
        migrations.AddField(
            model_name='rating',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='header',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
