# Generated by Django 5.0.6 on 2024-07-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('store', '0011_alter_rating_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
